# Vantage Configuration
framework: nextjs

# Bundle Analysis Configuration
bundle:
  # Analysis depth: deep (module-level, treemaps) or simple (size only)
  analysis: deep

  # Next.js output directory
  outputDir: .next

  # Generate treemap visualizations
  treemap: true

  # Size budgets for specific paths
  budgets:
    - path: "app/**/*.js"
      max: 100kb
    - path: "chunks/main-*.js"
      max: 150kb

  # Threshold percentages for regression detection
  thresholds:
    regression: 10    # Fail if bundle grows by more than 10%
    warning: 5        # Warn if bundle grows by 5-10%

  # Ignore patterns for bundle analysis
  ignore:
    - "**/node_modules/**"
    - "**/test/**"

# Runtime Performance Configuration
runtime:
  # Routes to test (required)
  routes:
    - /
    - /dashboard
    - /checkout

  # Routes to exclude from testing
  exclude:
    - "/api/**"
    - "/_next/**"

  # Thresholds for Core Web Vitals (in milliseconds)
  thresholds:
    lcp: 2500    # Largest Contentful Paint
    inp: 200      # Interaction to Next Paint
    cls: 0.1      # Cumulative Layout Shift
    tbt: 300      # Total Blocking Time

  # Lighthouse configuration
  lighthouse:
    numberOfRuns: 3           # Number of runs for averaging
    preset: desktop            # desktop or mobile
    throttling: fast-3g        # fast-3g, slow-4g, or offline
